// Originally auto-generated by Lovable to broker OAuth through Lovable Cloud.
// Self-hosted build: social login isn't configured yet, so this stubs the
// same shape (signInWithOAuth) instead of pulling in the Lovable Cloud SDK.

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (_provider: "google" | "apple" | "microsoft" | "lovable", _opts?: SignInOptions) => {
      return { error: new Error("Login social temporariamente indisponível") };
    },
  },
};
