/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalaCodeRouteImport } from './routes/sala.$code'
import { Route as ApiPublicLentesSfxRouteImport } from './routes/api/public/lentes-sfx'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaCodeRoute = SalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLentesSfxRoute = ApiPublicLentesSfxRouteImport.update({
  id: '/api/public/lentes-sfx',
  path: '/api/public/lentes-sfx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/landing': typeof LandingRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/landing': typeof LandingRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/landing': typeof LandingRoute
  '/sala/$code': typeof SalaCodeRoute
  '/api/public/lentes-sfx': typeof ApiPublicLentesSfxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/forgot-password'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/landing'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/forgot-password'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/landing'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/forgot-password'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/landing'
    | '/sala/$code'
    | '/api/public/lentes-sfx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContaRoute: typeof ContaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  LandingRoute: typeof LandingRoute
  SalaCodeRoute: typeof SalaCodeRoute
  ApiPublicLentesSfxRoute: typeof ApiPublicLentesSfxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala/$code': {
      id: '/sala/$code'
      path: '/sala/$code'
      fullPath: '/sala/$code'
      preLoaderRoute: typeof SalaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lentes-sfx': {
      id: '/api/public/lentes-sfx'
      path: '/api/public/lentes-sfx'
      fullPath: '/api/public/lentes-sfx'
      preLoaderRoute: typeof ApiPublicLentesSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContaRoute: ContaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  LandingRoute: LandingRoute,
  SalaCodeRoute: SalaCodeRoute,
  ApiPublicLentesSfxRoute: ApiPublicLentesSfxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
